### ISSUE TITLE
Banner nicht abgelehnt auf site24x7.com

### ISSUE THREAD

**Issue by two3d** [JobcenterTycoon/cookie-auto-decline#1]
Vielen Dank für Ihr Addon. Ich habe es auf site24x7.com getestet, aber es scheint das Banner nicht zu entfernen?

**Comment by JobcenterTycoon** [comment]
Hallo,

das Problem konnte reproduziert werden. Der Fix wird beim nächsten Addon Update verfügbar sein. Leider ist es nicht leicht solche invidiuellen Cookie Banner automatisch zu erkennen und abzulehnen, insbesondere wenn man zum Ablehnen erst in die Einstellungen muss. Eine automatische Erkennung von unbekannten Cookie Bannern anhand anderer Parameter ist allerdings in Planung um mehr abdecken zu können.

**Comment by two3d** [comment]
Ich verstehe die Schwierigkeit, danke für Ihre Antwort.
